---
driver:
  name: vagrant
  pre_create: vagrant box update --box bento/$KITCHEN_PLATFORM_NAME

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 1
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code
    environment: _default
  product_name: chef
  product_version: 14

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[docker_apache2_precedence_issue::default]
    verifier:
      inspec_tests:
        - test/integration/default